---
service_name: "mssql"
service_instance: "{{ service_name }}-{{ _apb_service_instance_id }}"
state: "present"

mssql_image: "docker.io/tchughesiv/mssql-server-linux"
mssql_image_tag: "{{ MSSQL_IMAGE_TAG | default('latest') }}"

mssql_data_volume_name: "{{ service_name }}-data"
mssql_data_path: "/var/opt"

mssql_db: "{{ MSSQL_DATABASE | default('sampledb') }}"
mssql_sa_pw: "{{ MSSQL_PASSWORD | default('yourStrong@Password') }}"

volume_size: "{{ MSSQL_DATA_STORAGE_SIZE | default('1') }}Gi"
memory_limit: "{{ MSSQL_MEMORY_LIMIT | default('2') }}Gi"
memory_request: "{{ MSSQL_MEMORY_REQUEST | default('1') }}Gi"
