---
service_name: "mssql-server"
mssql_image_tag: "{{ MSSQL_IMAGE_TAG | default('latest') }}"
mssql_image: "docker.io/tchughesiv/mssql-server-linux"
mssql_data_volume_name: "{{ service_name }}-data"
mssql_data_path: "/var/opt/mssql"
mssql_db: "{{ MSSQL_DATABASE | default('sampledb') }}"
mssql_sa_pw: "{{ MSSQL_PASSWORD | default('yourStrong@Password') }}"
memory_limit: "{{ MSSQL_MEMORY_LIMIT | default('2Gi') }}"
memory_request: "{{ MSSQL_MEMORY_REQUEST | default('1Gi') }}"
state: "present"
